### ISSUE TITLE
Overlap estimator bug

### ISSUE THREAD

**Issue by ThomasenQunasys** [QunaSys/quri-sdk#249]
This line sometimes throws a key error:
https://github.com/QunaSys/quri-parts/blob/407ae825f995c7db9afd0c2983c1932407ea4f29/packages/core/quri_parts/core/estimator/sampling/overlap_estimator.py#L37

This one too
https://github.com/QunaSys/quri-parts/blob/407ae825f995c7db9afd0c2983c1932407ea4f29/packages/core/quri_parts/core/estimator/sampling/overlap_estimator.py#L42

It seems kind of obvious in hindsight, but the `self._sampling_counts.keys()` should be checked before requesting a specific count.

**Comment by kwkbtr** [comment]
Replacing `[0]` with `.get(0, 0)` may be the easiest way to fix.
